server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wss?serverTimeZone=GMT%2b8
    username: root
    password: 19990212
mybatis:
  mapper-locations: classpath:mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
file:
  upload:
    path: /Users/lanhu/Desktop/Personal/springBoot-module/files/